/* ============================================================
   邮件回复决策助手 · 数据文件  data.js
   ⚠️  自动生成，请勿手工编辑。
   数据源：长表结构.md（82 条方案）
   生成命令：python3 tools/build-data.py
   术语译名：tools/glossary.en.json
   ============================================================ */

window.APP_DATA = {

  meta: {
    source: "长表结构.md",
    placeholder: "/",
    total: 82,
    categories: ["安全类", "服务类", "时效类", "需求类", "其他类"]
  },

  /* 中文术语 → 英文译名（仅用于界面展示；官方分类以中文原文为准） */
  glossary: {
    "AI机器人提供错误方案导致地址无法修改且包裹正在派送中无法修改造成的DNR": "DNR Caused by AI Chatbot Misguidance (Address Could Not Be Changed, Parcel Already Out for Delivery)",
    "POD不可见包裹破损": "Damage Not Visible in POD",
    "POD不合规": "POD Non-compliant",
    "POD可见包裹破损": "Damage Visible in POD",
    "POD合规": "POD Compliant",
    "POD合规多次进线": "Multiple Contacts with Compliant POD",
    "POD和签收类型的解释": "Explanation of POD and Delivery Types",
    "POD图片侵犯隐私": "POD Photo Privacy Violation",
    "不要包裹且可退给商家（包裹未签收）": "No Longer Wants the Parcel, Returnable to Seller (Not Delivered)",
    "丢失类": "Loss",
    "二次进线（理赔：确认DNR+有证据）": "Second Contact (Claim: DNR Confirmed + Evidence Available)",
    "二次进线（要证据）": "Second Contact (Evidence Requested)",
    "二次进线（调查中，暂无反馈）": "Second Contact (Investigation Ongoing, No Update Yet)",
    "信息修改": "Information Amendment",
    "修改信息-下单信息不完整": "Information Amendment — Incomplete Order Details",
    "修改地址-核实地址": "Address Change — Verify Address",
    "修改地址-要谷歌地图可查地址": "Address Change — Address Must Be Findable on Google Maps",
    "催派": "Delivery Follow-up",
    "催派-不可抗力（车抛锚等意外）": "Follow-up — Force Majeure (Vehicle Breakdown, etc.)",
    "催派-刚到转运中心": "Follow-up — Just Arrived at Transit Hub",
    "催派-客服回复邮件时发现包裹已签收": "Follow-up — Parcel Found Delivered While Replying",
    "催派-异常情况": "Follow-up — Exceptional Circumstances",
    "催派-有内部轨迹无外部轨迹": "Follow-up — Internal Scans Only, No External Tracking",
    "催派-轨迹断更2-7天": "Follow-up — No Scan for 2–7 Days",
    "催派-轨迹断更7-14天": "Follow-up — No Scan for 7–14 Days",
    "催派-轨迹断更>14天": "Follow-up — No Scan for More Than 14 Days",
    "催派已签收": "Follow-up — Already Delivered",
    "催派类": "Delivery Follow-up",
    "其他类": "Others",
    "前一封邮件回复错误": "Previous Reply Was Incorrect",
    "包裹以外的财物损坏": "Property Damage Beyond the Parcel",
    "包裹内少件": "Missing Items in the Parcel",
    "包裹异味": "Parcel Has an Odour",
    "包裹的收件人名字和手机号正确但地址不对": "Correct Name and Phone Number, Wrong Address",
    "包裹确认被抢/丢失（未签收）": "Parcel Confirmed Stolen / Lost (Not Delivered)",
    "包裹被打开": "Parcel Opened",
    "包裹被抢/丢失": "Parcel Stolen / Lost",
    "单纯进线信息告知（邮件）": "Courtesy Notices (Email)",
    "合作咨询/服务咨询": "Partnership / Service Enquiries",
    "告知已修改信息（转运中心签入前）": "Amendment Confirmed (Before Transit Hub Check-in)",
    "告知已修改信息（转运中心签入后）": "Amendment Confirmed (After Transit Hub Check-in)",
    "告知收到偏好时间段": "Preferred Time Window Received",
    "商品破损（工作台确认破损，退回客户）": "Damaged Goods (Damage Confirmed by Operations, Returned to Customer)",
    "商品质量问题": "Product Quality Issue",
    "外包装完好内物少件": "Intact Packaging, Missing Contents",
    "外包装完好内物破损": "Intact Packaging, Damaged Contents",
    "外包装完好内物破损（POD不可见包裹破损）": "Intact Packaging, Damaged Contents (Damage Not Visible in POD)",
    "外包装完好内物破损（POD可见包裹破损）": "Intact Packaging, Damaged Contents (Damage Visible in POD)",
    "外包装完好内物错件": "Intact Packaging, Wrong Contents",
    "外包装破损内物完好": "Damaged Outer Packaging, Intact Contents",
    "外包装破损内物破损/少件": "Damaged Packaging, Damaged / Missing Contents",
    "外包装破损内物破损/少件（POD不可见包裹破损）": "Damaged Packaging, Damaged / Missing Contents (Damage Not Visible in POD)",
    "外包装破损内物破损/少件（POD可见包裹破损）": "Damaged Packaging, Damaged / Missing Contents (Damage Visible in POD)",
    "多次进线（让收件人看监控）": "Multiple Contacts (Ask Recipient to Review CCTV)",
    "安全类": "Security",
    "客户查件": "Shipment Enquiry",
    "工作台确认破损（未签收）": "Damage Confirmed by Operations (Not Delivered)",
    "快件找回": "Parcel Recovered",
    "快递员偷盗": "Suspected Theft by Courier",
    "快递员取件": "Courier Pickup",
    "快递员暴力投递": "Rough Handling by Courier",
    "快递员服务态度差": "Courier's Poor Attitude",
    "想要自提": "Wants to Collect in Person",
    "感谢(包裹未签收)": "Thanks (Not Delivered)",
    "感谢+道歉（包裹已签收）": "Thanks + Apology (Delivered)",
    "感谢（包裹已签收）": "Thanks (Delivered)",
    "投简历面试": "Job Application / Interview",
    "投诉客服": "Agent Complaints",
    "投诉客服-服务态度": "Agent Complaint — Attitude",
    "投诉快递员": "Courier Complaints",
    "投诉快递员-暴力投递（无破损/无证据）": "Courier Complaint — Rough Handling (No Damage / No Evidence)",
    "投诉快递员-服务态度": "Courier Complaint — Poor Attitude",
    "投诉快递员-派送失败原因与实际不符": "Courier Complaint — Delivery Failure Reason Mismatch",
    "投诉快递员-疑似偷窃": "Courier Complaint — Suspected Theft",
    "投递失败（收件人不在家）": "Delivery Failed (Recipient Not at Home)",
    "投递失败：大楼关闭/周末/节假日": "Delivery Failed: Building Closed / Weekend / Public Holiday",
    "投递失败：无法进入/无法投递": "Delivery Failed: No Access / Unable to Deliver",
    "收件人不理解“以此邮件为凭证去找商家退款”": "Recipient Unsure About Using This Email as Proof for a Seller Refund",
    "收件人填错地址（已签收）": "Wrong Address Provided by Recipient (Delivered)",
    "收到错误包裹": "Wrong Parcel Received",
    "无单号/单号错误": "No / Invalid Tracking Number",
    "无运单号": "No Tracking Number",
    "时效内催派【外部轨迹断更≤2天】": "Within SLA — No External Scan ≤2 Days",
    "时效外催派【外部轨迹断更>2天】": "Over SLA — No External Scan >2 Days",
    "时效类": "Timeliness",
    "服务态度问题": "Agent Attitude Issue",
    "服务类": "Service",
    "未按要求妥投": "Not Delivered as Instructed",
    "查件-包裹未到SPX仓库": "Enquiry — Parcel Not Yet at SPX Warehouse",
    "查件-完成清关但未到转运中心": "Enquiry — Customs Cleared, Not Yet at Transit Hub",
    "查件-已退回商家": "Enquiry — Returned to Seller",
    "查件-转运中心签入前": "Enquiry — Before Transit Hub Check-in",
    "正向反馈": "Positive Feedback",
    "派送失败原因与实际不符": "Delivery Failure Reason Mismatch",
    "理赔": "Claims",
    "用户要求理赔": "Customer Requests Compensation",
    "疑似丢失（道歉＋赔偿）": "Suspected Loss (Apology + Compensation)",
    "真诚道歉（包裹未签收）": "Sincere Apology (Not Delivered)",
    "破损类": "Damage",
    "签入前查件": "Enquiry — Before Check-in",
    "签收前要求不派送": "No Delivery Requested Before Delivery",
    "签收后要求退件": "Return Requested After Delivery",
    "签收未收到": "Delivered but Not Received",
    "系统不满意": "System Dissatisfaction",
    "系统体验反馈": "System Experience Feedback",
    "系统问题反馈": "System Feedback",
    "表扬客服人员": "Compliment: Agent",
    "表扬快递员": "Compliment: Courier",
    "要求退件": "Return Requests",
    "询问具体日期": "Asking for a Specific Date",
    "询问具体时间": "Asking for a Specific Time",
    "询问发件人": "Asking About the Sender",
    "询问商家": "Asking About the Seller",
    "询问快递员": "Asking About the Courier",
    "运单号不完整": "Incomplete Tracking Number",
    "运单号错误": "Incorrect Tracking Number",
    "退件后查件": "Enquiry — After Return",
    "退回转运中心后重派": "Redelivery After Return to Transit Hub",
    "重新派送": "Redelivery",
    "错分件": "Missorted Parcel",
    "错误投递包裹待取件": "Mis-delivered Parcel Awaiting Collection",
    "需求变更": "Change Requests",
    "需求类": "Requests",
    "面单一致": "Waybill Label Consistent",
    "面单不一致": "Waybill Label Inconsistent",
    "首次进线(检查周围）": "First Contact (Check the Surroundings)",
    "首次进线（开始调查+给证据）": "First Contact (Start Investigation + Request Evidence)"
  },

  scenarios: [
    {
      no: 1,
      l1: "安全类",
      l2: "丢失类",
      l3: "包裹被抢/丢失",
      pod: "/",
      sub: "包裹确认被抢/丢失（未签收）",
      plan: "告知客户包裹被抢/丢失，建议联系上游客户处理退款/补发事宜",
      sop: "",
      zh: "您好：\n我是 SpeedX 客服部门的Jason 。\n我们遗憾地通知您，您的订单在运往我们当地站点的途中被盗。\n我们理解这一消息非常令人不快和沮丧，并对所发生的事情深表歉意。我们已将该事件列为最高优先级，并已向地方当局报案，当局已展开调查。\n作为承运商，我们正在积极与执法部门合作。然而，由于包裹已无法找回，关于订单的退款或重新发货，您需要直接联系您购买商品的卖家。我们建议您尽快联系您下单的网站或商店的客服，告知他们这一情况。他们将协助您完成相应的售后流程。\n对于这一超出我们控制范围的事件所造成的不愉快体验，我们再次表示歉意。\n此致,\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nWe regret to inform you that your order was stolen during transport to our local station.\nWe understand that this news is very unpleasant and frustrating, and we sincerely apologize for what happened. We have given the incident the highest priority and have already filed a report with the local authorities, who have launched an investigation.\nAs the courier, we are actively cooperating with law enforcement. However, since the package can no longer be recovered, regarding any refund or reshipment of the order, you will need to contact the seller from whom you made the purchase directly. We recommend that you contact the customer service of the website or store where you placed the order as soon as possible, informing them of the situation. They will assist you with the corresponding after-sales procedure.\nWe apologize again for the unpleasant experience caused by this event beyond our control.\nBest regards,\nJason"
    },
    {
      no: 2,
      l1: "安全类",
      l2: "丢失类",
      l3: "包裹被抢/丢失",
      pod: "/",
      sub: "疑似丢失（道歉＋赔偿）",
      plan: "安抚致歉 → 与派送伙伴确认包裹丢失 → 出具理赔证明 PDF → 引导向卖家申请退款",
      sop: "催派",
      zh: "您好：\n我是 SpeedX 客服部门的 Jason。\n非常抱歉地通知您，经与派送伙伴核查，我们确认您的包裹已在运输过程中丢失。对于由此给您带来的不便与失望，我们深表歉意。\n由于 SpeedX 是物流服务商，我们无法直接为您办理退款，但会为您出具理赔证明（见本邮件附件 PDF）。请您将该证明转发给您购买商品的卖家或电商平台，作为申请退款或赔偿的依据。\n我们已将该情况上报，并将持续改进作业流程，避免类似情况再次发生。如您需要其他协助，请回复此邮件。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nWe are very sorry to inform you that, after verification with our delivery partner, your package has been confirmed lost in transit. We sincerely apologize for the inconvenience and disappointment this has caused you.\nAs SpeedX is a logistics service provider, we cannot process a refund directly. However, we will issue a proof of claim for you (see the PDF attached to this email). Please forward it to the seller or the e-commerce platform where you made your purchase as supporting evidence for your refund or compensation request.\nWe have reported this case and will continue to improve our handling procedures to prevent this from happening again. If you need any further assistance, please reply to this email.\nBest regards,\nJason"
    },
    {
      no: 3,
      l1: "安全类",
      l2: "丢失类",
      l3: "签收未收到",
      pod: "POD合规",
      sub: "首次进线(检查周围）",
      plan: "核实POD图片合规→引导用户检查周围或其他指定投递地点、与邻居、同住的居民，或所在大楼的门卫或保安人员",
      sop: "",
      zh: "您好：\n我是 SpeedX 客服部门的Jason。\n感谢您联系我们。您的包裹显示已妥投；如果您尚未收到，请进行以下核查：\n1. 检查您的住所内及附近的区域（前门、门廊、邮件室等）。\n2. 请询问邻居是否代收。\n3. 包裹可能已根据您在下单或发货时告知的偏好/授权进行投递（例如，交给门卫，或放在您指定的附近地点）。\n完成上述核查后，如果仍未找到包裹，请检查您是否有视频监控资料以核实所发生的情况。如果没有，请通过电子邮件联系我们，以便进行更深入的核查。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nThank you for contacting us.Your package is shown as delivered,if you have not received it, please carry out the following checks:\n1.Check your mailbox, or areas within and around your residence (front door, porch, mailroom, etc.).\n2.Kindly ask a neighbor whether they collected it.\n3.It is possible that the package was delivered according to your preferences/authorizations provided at the time of ordering or shipping (e.g., leaving it with a concierge or in a nearby place specified by you).\nAfter carrying out these checks, if the package has still not been found, please check whether you have video surveillance footage to verify what happened. If not, contact us by email so we can carry out more thorough checks.\nBest regards,\nJason"
    },
    {
      no: 4,
      l1: "安全类",
      l2: "丢失类",
      l3: "签收未收到",
      pod: "POD合规",
      sub: "二次进线（要证据）",
      plan: "核实POD图片合规→引导用户检查周围或其他指定投递地点、与邻居、同住的居民，或所在大楼的门卫或保安人员",
      sop: "",
      zh: "您好：\n我是 SpeedX 客服部门的Jason。\n感谢您联系我们。我们的记录显示，您的包裹已投递至订单上的地址。\n如果您没有收到，请提供佐证材料，例如您的门/单元号照片、监控录像，或物业管理出具的证明。请将任何相关信息分享给我们，以便我们进一步调查。\n感谢您的理解与配合。我们会及时向您更新进展。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nThank you for contacting us. Our records show that your shipment was delivered for at the address on the order.\nIf you did not receive it, please provide supporting evidence, such as a photo of your door/unit number, CCTV footage, or a building management statement. Please share any relevant information with us so we can look into this further.\nThank you for your understanding and cooperation. We will keep you updated.\nBest regards,\nJason"
    },
    {
      no: 5,
      l1: "安全类",
      l2: "丢失类",
      l3: "签收未收到",
      pod: "POD合规",
      sub: "AI机器人提供错误方案导致地址无法修改且包裹正在派送中无法修改造成的DNR",
      plan: "核实POD图片合规→引导用户检查周围或其他指定投递地点、与邻居、同住的居民，或所在大楼的门卫或保安人员",
      sop: "",
      zh: "您好，\n我是 SpeedX 客服部门的 Jason。\n非常抱歉给您带来不便。我们的AI聊天机器人给出了错误指引，导致您选择了退货，而不是更改地址。当时包裹已经进入派送流程，因此无法更改地址。包裹现在已经派送至您下单的地址。\n由于包裹已派送，请您前往订单地址取件。我们诚挚致歉。我们正在修复AI聊天机器人并改进我们的派送服务，以防止此类情况再次发生。\n如果您需要进一步帮助，请联系我们。\n此致，\nJason",
      en: "Dear Customer,\nThis is Jason from SpeedX Customer Service department.\nWe are very sorry for the inconvenience. Our AI chatbot gave incorrect guidance, which led you to choose a return instead of an address change. At that time, the parcel was already out for delivery, so the address could not be changed. The parcel has now been delivered to the address on your order.\nSince the parcel has been delivered, please go to the order address to pick it up. We sincerely apologize. We are fixing the AI chatbot and improving our delivery service to prevent this from happening again.\nIf you need further help, please contact us.\nBest regards,\nJason"
    },
    {
      no: 6,
      l1: "安全类",
      l2: "丢失类",
      l3: "签收未收到",
      pod: "POD合规",
      sub: "收件人填错地址（已签收）",
      plan: "核实POD图片合规→引导用户检查周围或其他指定投递地点、与邻居、同住的居民，或所在大楼的门卫或保安人员",
      sop: "",
      zh: "您好：\n我是 SpeedX 客服部的 Jason。\n非常抱歉给您带来不便。作为快递公司，我们只能派送至订单中注明的地址。\n我们建议您核实所提供的地址，并直接联系卖家，以就此找到解决方案。此外，我们也建议您前往订单中注明的地址，尝试找回包裹。\n此致\nJason",
      en: "Incorrect recipient address (delivered)\nDear,\nThis is Jason from SpeedX Customer Service department.\nWe are very sorry for the inconvenience. As a courier company, we can only deliver to the address indicated in the order.\nWe advise you to verify the address provided and to contact the seller directly to find a solution regarding this matter.We also suggest that you go to the address indicated in the order to try to retrieve the package.\nBest regards,\nJason"
    },
    {
      no: 7,
      l1: "安全类",
      l2: "丢失类",
      l3: "签收未收到",
      pod: "POD合规",
      sub: "多次进线（让收件人看监控）",
      plan: "多次进线 → 请收件人查看监控或与邻居/物业确认 → 提供证据以便进一步核查",
      sop: "签收未收到",
      zh: "您好：\n我是 SpeedX 客服部门的 Jason。\n感谢您再次联系我们。我们的记录显示，您的包裹已投递至订单上的地址，且投递照片（POD）合规。\n为了进一步核实，可否请您查看住所或楼栋的监控录像，确认包裹的签收过程？如您没有监控，也请您再次与邻居、同住人员或楼栋管理员确认是否有人代收。\n如您能提供相关监控或其他证明材料，我们将立即展开进一步核查。感谢您的理解与配合。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nThank you for contacting us again. Our records show that your package was delivered to the address on the order and that the proof-of-delivery photo (POD) is compliant.\nTo look into this further, could you please check any CCTV footage at your residence or building to confirm how the package was collected? If you do not have CCTV, please also check once more with your neighbours, household members, or the building manager to see whether someone collected it on your behalf.\nIf you can provide the relevant footage or other supporting documents, we will start a further verification immediately. Thank you for your understanding and cooperation.\nBest regards,\nJason"
    },
    {
      no: 8,
      l1: "安全类",
      l2: "丢失类",
      l3: "签收未收到",
      pod: "POD合规",
      sub: "POD合规多次进线",
      plan: "多次进线且 POD 合规 → 说明已完成多轮核查 → 建议向执法部门报案并提供记录",
      sop: "签收未收到",
      zh: "您好：\n我是 SpeedX 客服部门的 Jason。\n感谢您多次与我们联系。您的包裹显示已妥投，投递照片（POD）合规，我们此前也已为您完成多轮核查。\n由于包裹在派送完成后发生的遗失已超出我司作为承运方的责任范围，我们建议您向当地执法部门报案，并将报案记录提供给我们；同时您也可以联系卖家或电商平台说明情况并申请退款。如有监控录像能够证明包裹被他人取走，请一并提供，我们会继续协助核查。\n如有任何其他问题，请回复此邮件。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nThank you for contacting us several times. Your package is shown as delivered and the proof-of-delivery photo (POD) is compliant; we have already carried out multiple checks for you.\nAs the loss occurred after delivery was completed, it falls outside the scope of our liability as a carrier. We suggest that you file a report with your local law enforcement authorities and share the report with us. You may also contact the seller or the e-commerce platform to explain the situation and request a refund. If you have CCTV footage showing that the package was taken by someone else, please provide it as well and we will continue to assist with the verification.\nIf you have any other questions, please reply to this email.\nBest regards,\nJason"
    },
    {
      no: 9,
      l1: "安全类",
      l2: "丢失类",
      l3: "签收未收到",
      pod: "POD不合规",
      sub: "首次进线（开始调查+给证据）",
      plan: "核实POD图片不合规→上报问题件",
      sop: "",
      zh: "您好：\n我是 SpeedX 客服部门的Jason。\n感谢您的邮件。我们对您遇到的情况深感抱歉，并理解您的感受。\n我们将尽最大努力联系我们的合作伙伴，并调查您包裹的状态。为便于调查，请您提供相关证据/凭证，例如您的门/单元号照片、监控录像，或物业管理出具的证明。可能需要至少 2 天（如果临近周末或节假日，调查时间将延长约两天）。之后，最好请您通过电子邮件联系我们，以核实包裹的处理结果。\n再次为给您带来的不便致歉。感谢您的理解与配合。如果您有其他问题，请通过电子邮件联系我们。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nThank you for your email. We are very sorry for the situation you have encountered and we understand how you feel.\nWe will do our best to contact our partner and investigate the status of your package. It may take at least 2 days (if weekends or holidays are approaching, the investigation time will be extended by about two days). After that, it would be best for you to contact us by email to check the outcome of the package.\nWe apologize again for the inconvenience.Thank you for your understanding and cooperation. If you have any other questions, please contact us by email.\nBest regards,\nJason"
    },
    {
      no: 10,
      l1: "安全类",
      l2: "丢失类",
      l3: "签收未收到",
      pod: "POD不合规",
      sub: "二次进线（调查中，暂无反馈）",
      plan: "核实POD图片不合规→上报问题件",
      sop: "",
      zh: "您好：\n我是 SpeedX 客服部门的 Jason。\n特此通知您，核查仍在进行中，我们尚未收到快递公司的回复。如果您能再给我们几天时间来完成核查，我们将非常感激。\n感谢您的理解，我们一收到任何更新就会联系您。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nWe inform you that the verification is still in progress and we have not yet received a response from the courier. We would be very grateful if you could grant us a few more days to complete the checks.\nWe thank you for your understanding and will contact you as soon as we receive any updates.\nBest regards,\nJason"
    },
    {
      no: 11,
      l1: "安全类",
      l2: "丢失类",
      l3: "签收未收到",
      pod: "POD不合规",
      sub: "二次进线（理赔：确认DNR+有证据）",
      plan: "核实POD图片不合规→上报问题件",
      sop: "",
      zh: "您好：\n我是 SpeedX 客服部门的 Jason。\n经核查，快递公司提供的投递证明可能无效。请将本邮件作为您向卖家申请退款或赔偿的依据。\n感谢您的理解。我们再次致歉，并随时为您服务。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nFollowing the checks carried out, it appears that the proof of delivery provided by the courier may not be valid. Please use this email as the basis for your refund or compensation claim with the seller.\nThank you for your understanding. We apologize again and remain at your disposal.\nBest regards,\nJason"
    },
    {
      no: 12,
      l1: "安全类",
      l2: "丢失类",
      l3: "签收未收到",
      pod: "POD不合规",
      sub: "收件人不理解“以此邮件为凭证去找商家退款”",
      plan: "核实POD图片不合规→上报问题件",
      sop: "",
      zh: "您好：\n我是 SpeedX 客服部的 Jason。\n本邮件可作为您申请退款或赔偿的支持性证据。由于 SpeedX 是一家物流公司，我们无法直接处理退款，也无法代表卖家作出赔偿。但是，根据我们的核查，快递员提供的签收证明可能无效。因此，您可以将本邮件转发给卖家或电商平台，请他们根据此信息审核您的退款或赔偿申请。\n对于给您带来的不便，我们深表歉意，并感谢您的理解。\n此致\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nThis email can serve as supporting evidence for your refund or compensation request. Since SpeedX is a logistics company, we cannot directly process refunds or issue compensation on behalf of the seller. However, based on our checks, the proof of delivery provided by the courier may not be valid. You may therefore forward this email to the seller or the e-commerce platform and ask them to review your refund or compensation request based on this information.\nWe sincerely apologize for the inconvenience and thank you for your understanding.\nBest regards,\nJason"
    },
    {
      no: 13,
      l1: "安全类",
      l2: "丢失类",
      l3: "快件找回",
      pod: "/",
      sub: "快件找回",
      plan: "核实包裹已找回 → 安排重新派送 → 安抚客户耐心等待",
      sop: "",
      zh: "您好：\n我是 SpeedX 客服部门的 Jason。\n感谢您的耐心等待。我们很高兴地通知您，此前在运输过程中暂时无法定位的包裹已经找回，目前正在我们的站点处理中。\n我们将尽快为您安排重新派送，预计在 1–3 天内送达。请您保持电话畅通，以便快递员与您联系。\n对于此前给您带来的担忧与不便，我们深表歉意。如有任何问题，请回复此邮件。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nThank you for your patience. We are pleased to inform you that the package that could not be located during transit has now been found and is being processed at our station.\nWe will arrange the redelivery as soon as possible, within 1–3 days. Please keep your phone available so that the courier can contact you.\nWe sincerely apologize for the concern and inconvenience caused. If you have any questions, please reply to this email.\nBest regards,\nJason"
    },
    {
      no: 14,
      l1: "安全类",
      l2: "丢失类",
      l3: "收到错误包裹",
      pod: "/",
      sub: "包裹的收件人名字和手机号正确但地址不对",
      plan: "核实面单信息不一致 →上报问题件",
      sop: "",
      zh: "您好：\n我是 SpeedX 客服部的 Jason。\n感谢您的来信。对于您遇到的情况，我们非常抱歉，也理解您的感受。\n很抱歉给您带来不便。作为一家物流公司，我们仅负责派送服务。如果包裹上的派送地址与您下单时提供的地址不一致，我们诚挚建议您直接联系您购买商品的商家或电商平台，以便找到合适的解决方案。\n再次为给您带来的不便致歉，并感谢您的理解。\n此致\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nThank you for your email. We are very sorry for the situation you have encountered and we understand how you feel.\nWe are sorry for the inconvenience. As a logistics company, we handle delivery services exclusively. If the delivery address on the parcel does not match the address you provided when placing your order, we kindly invite you to contact the seller or e-commerce platform where you made the purchase directly, so that an appropriate solution can be found.\nWe apologize again for the inconvenience and appreciate your understanding.\nBest regards,\nJason"
    },
    {
      no: 15,
      l1: "安全类",
      l2: "丢失类",
      l3: "外包装完好内物错件",
      pod: "/",
      sub: "面单一致",
      plan: "核实面单一致→判定疑似上游客户发错→告知联系上游客户处理",
      sop: "",
      zh: "您好：\n我是 SpeedX 客服部门的 Jason。\n感谢您的来信。对您遇到的情况我们非常抱歉，我们理解您的感受。\n很抱歉给您带来不便。作为一家物流公司，我们仅负责配送服务。如果您收到的商品与订购的不符，我们建议您直接联系您购买商品的卖家或电商平台，以便找到合适的解决方案。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nThank you for your email. We are very sorry for the situation you have encountered and we understand how you feel.\nWe are sorry for the inconvenience. As a logistics company, we handle delivery services exclusively. If the goods received do not match what was ordered, we kindly invite you to contact the seller or e-commerce platform where you made the purchase directly, so that an appropriate solution can be found.\nBest regards,\nJason"
    },
    {
      no: 16,
      l1: "安全类",
      l2: "丢失类",
      l3: "外包装完好内物错件",
      pod: "/",
      sub: "面单不一致",
      plan: "核实面单一致→判定疑似上游客户发错→告知联系上游客户处理",
      sop: "",
      zh: "您好：\n我是 SpeedX 客服部门的 Jason。\n感谢您的来信。对您遇到的情况我们非常抱歉，我们理解您的感受。\n很抱歉给您带来不便。作为一家物流公司，我们仅负责配送服务。我们建议您直接联系您购买商品的卖家或电商平台，以便找到合适的解决方案。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nThank you for your email. We are very sorry for the situation you have encountered and we understand how you feel.\nWe are sorry for the inconvenience. As a logistics company, we handle delivery services exclusively.We kindly invite you to contact the seller or e-commerce platform where you made the purchase directly, so that an appropriate solution can be found.\nBest regards,\nJason"
    },
    {
      no: 17,
      l1: "安全类",
      l2: "丢失类",
      l3: "外包装完好内物少件",
      pod: "/",
      sub: "包裹内少件",
      plan: "核实外包装完好、内物缺少→告知联系上游客户处理",
      sop: "",
      zh: "您好：\n我是 SpeedX 客服部门的 Jason。\n我们非常抱歉给您带来的不便。如果您发现包裹中缺少物品，原因可能是原始包装不合适。\n另一方面，如果您认为包裹是被快递员损坏或擅自拆动的，请您向我们提供照片或视频作为证据，我们将据此核实情况。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nWe are very sorry for the inconvenience you have encountered. If you have noticed that something is missing from your package, the cause may be due to unsuitable original packaging.\nIf, on the other hand, you believe that the package was damaged or tampered with by the courier, we invite you to provide us with photos or videos as proof, and we will verify the situation accordingly.\nBest regards,\nJason"
    },
    {
      no: 18,
      l1: "安全类",
      l2: "破损类",
      l3: "工作台确认破损（未签收）",
      pod: "/",
      sub: "商品破损（工作台确认破损，退回客户）",
      plan: "工作台确认为破损件 → 告知不再派送、包裹退回 → 出具相关证明 → 引导联系卖家理赔",
      sop: "催派",
      zh: "您好：\n我是 SpeedX 客服部门的 Jason。\n感谢您联系我们。经核查，您的包裹在运输过程中出现破损，目前已由我方工作台确认为破损件，将不再继续派送。对于由此给您带来的不便，我们深表歉意。\n我们将按流程将包裹退回处理，并为您出具相关证明。由于 SpeedX 是物流服务商，无法直接为您办理退款或补发，请您联系购买商品的卖家或电商平台，凭本邮件申请退款、补发或理赔。\n我们已将该情况上报，以避免类似问题再次发生。如有任何问题，请回复此邮件。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nThank you for contacting us. Following our checks, your package was damaged in transit. It has now been confirmed as a damaged item by our operations desk and will not be delivered. We sincerely apologize for the inconvenience.\nThe package will be returned in accordance with our procedure, and we will issue the relevant documentation for you. As SpeedX is a logistics service provider, we cannot process a refund or reshipment directly. Please contact the seller or the e-commerce platform where you made your purchase and use this email to apply for a refund, replacement, or compensation.\nWe have reported this case in order to prevent similar issues from happening again. If you have any questions, please reply to this email.\nBest regards,\nJason"
    },
    {
      no: 19,
      l1: "安全类",
      l2: "破损类",
      l3: "外包装破损内物完好",
      pod: "",
      sub: "外包装破损内物完好",
      plan: "安抚客户 → 说明外包装破损但内物完好不影响正常使用",
      sop: "",
      zh: "您好：\n我是 SpeedX 客服部门的 Jason。\n感谢您的来信。对于包裹外包装在运输过程中出现破损，给您带来的担心与不便，我们深表歉意。\n经核实，包裹内件完好且可以正常使用。外包装破损通常是在运输、分拣或搬运过程中受到挤压所致，不影响内件本身。\n我们已将该情况记录并反馈至相关团队，以加强包装与操作规范，避免类似情况再次发生。如内件存在任何问题，请提供照片或视频，我们将立即为您核实处理。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nThank you for your message. We sincerely apologize for the concern and inconvenience caused by the damage to the outer packaging during transit.\nFollowing our checks, the contents of the package are intact and fully usable. Damage to the outer packaging is usually caused by pressure during transport, sorting, or handling, and does not affect the items inside.\nWe have recorded this issue and shared it with the relevant team so that packaging and handling standards can be improved to prevent this from happening again. If there is any problem with the contents, please send us photos or videos and we will verify it immediately.\nBest regards,\nJason"
    },
    {
      no: 20,
      l1: "安全类",
      l2: "破损类",
      l3: "外包装破损内物破损/少件",
      pod: "POD可见包裹破损",
      sub: "外包装破损内物破损/少件（POD可见包裹破损）",
      plan: "告知联系上游客户处理",
      sop: "",
      zh: "您好：\n我是 SpeedX 客服部门的 Jason。\n感谢您的来信。对于您收到的包裹出现外包装破损、内件破损或缺少的情况，我们深表歉意。\n经核查，快递员拍摄的投递照片（POD）中可以确认包裹在投递时已存在破损痕迹，因此该情况很可能发生在运输或分拣环节。作为物流公司，我们负责运输与派送，无法直接为您办理退款或补发。\n我们建议您尽快联系您购买商品的卖家或电商平台，并将本邮件及投递照片作为凭证，以便他们为您处理退款、补发或理赔事宜。\n再次为给您带来的不便致歉。如有任何问题，请回复此邮件。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nThank you for your message. We sincerely apologize that the package you received arrived with damaged outer packaging and damaged or missing contents.\nFollowing our checks, the proof-of-delivery photos (POD) taken by the courier show that the package was already damaged at the time of delivery, which means the damage most likely occurred during transport or sorting. As a logistics company, we are responsible for transport and delivery and cannot process a refund or reshipment directly.\nWe recommend that you contact the seller or the e-commerce platform where you made your purchase and use this email together with the delivery photos as supporting evidence, so that they can handle your refund, replacement, or claim.\nWe apologize again for the inconvenience. If you have any questions, please reply to this email.\nBest regards,\nJason"
    },
    {
      no: 21,
      l1: "安全类",
      l2: "破损类",
      l3: "外包装破损内物破损/少件",
      pod: "POD不可见包裹破损",
      sub: "外包装破损内物破损/少件（POD不可见包裹破损）",
      plan: "核实外包装破损、内物破损/少件→POD图片无法看出破损，安抚解释→引导提供监控视频等证据",
      sop: "",
      zh: "您好：\n我是 SpeedX 客服部门的 Jason。\n感谢您的来信。对于您的包裹出现外包装破损、内件破损或缺少的情况，我们深表歉意。\n经核查，快递员拍摄的投递照片（POD）中未能看出包裹破损的痕迹，因此我们暂时无法确认破损发生的环节。为了进一步核实，请您提供以下材料：包裹外包装及内件的照片或视频、开箱视频（如有），以及能够反映包裹签收过程的监控录像。\n收到上述材料后，我们将立即展开核查。如确属运输过程中造成，我们会为您出具相应的说明，以便您向卖家或电商平台申请退款、补发或理赔。\n再次为给您带来的不便致歉。感谢您的理解与配合。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nThank you for your message. We sincerely apologize that the package you received arrived with damaged outer packaging and damaged or missing contents.\nFollowing our checks, the proof-of-delivery photos (POD) taken by the courier do not show any damage to the package, so we are currently unable to determine at which stage the damage occurred. To carry out a further review, please provide the following: photos or videos of the outer packaging and the contents, an unboxing video (if available), and any CCTV footage showing the delivery or collection of the package.\nOnce we receive these materials, we will start the verification immediately. If the damage is confirmed to have occurred during transport, we will provide a statement for you to submit a refund, replacement, or claim request to the seller or the e-commerce platform.\nWe apologize again for the inconvenience. Thank you for your understanding.\nBest regards,\nJason"
    },
    {
      no: 22,
      l1: "安全类",
      l2: "破损类",
      l3: "外包装完好内物破损",
      pod: "POD可见包裹破损",
      sub: "外包装完好内物破损（POD可见包裹破损）",
      plan: "告知联系上游客户处理",
      sop: "",
      zh: "您好：\n我是 SpeedX 客服部门的 Jason。\n感谢您的来信。对于您收到的包裹出现内件破损的情况，我们深表歉意。\n经核查，快递员拍摄的投递照片（POD）中可以看到包裹存在破损痕迹，该破损很可能发生在运输或分拣过程中。作为物流公司，我们负责运输与派送，无法直接为您办理退款或补发。\n我们建议您联系您购买商品的卖家或电商平台，并将本邮件及投递照片作为凭证，以便他们为您处理退款、补发或理赔事宜。\n再次为给您带来的不便致歉。如有任何问题，请回复此邮件。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nThank you for your message. We sincerely apologize that the package you received contained damaged contents.\nFollowing our checks, the proof-of-delivery photos (POD) taken by the courier show signs of damage to the package, which most likely occurred during transport or sorting. As a logistics company, we are responsible for transport and delivery and cannot process a refund or reshipment directly.\nWe recommend that you contact the seller or the e-commerce platform where you made your purchase and use this email together with the delivery photos as supporting evidence, so that they can handle your refund, replacement, or claim.\nWe apologize again for the inconvenience. If you have any questions, please reply to this email.\nBest regards,\nJason"
    },
    {
      no: 23,
      l1: "安全类",
      l2: "破损类",
      l3: "外包装完好内物破损",
      pod: "POD不可见包裹破损",
      sub: "外包装完好内物破损（POD不可见包裹破损）",
      plan: "核实外包装完好、内物破损→告知联系上游客户处理",
      sop: "",
      zh: "您好：\n我是 SpeedX 客服部门的 Jason。\n感谢您的来信。对于您收到的包裹出现内件破损的情况，我们深表歉意。\n经核查，包裹外包装完好，快递员拍摄的投递照片（POD）中也没有发现破损痕迹，因此该破损可能源于发货时的包装不当或商品本身状况。作为物流公司，我们仅负责运输与派送，无法直接为您办理退款或补发。\n我们建议您直接联系卖家或电商平台，说明内件破损的情况并申请退款、补发或理赔。如有需要，我们可以为您提供本次投递的相关凭证。\n再次为给您带来的不便致歉。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nThank you for your message. We sincerely apologize that the package you received contained damaged contents.\nFollowing our checks, the outer packaging is intact and the proof-of-delivery photos (POD) taken by the courier show no signs of damage, so the damage may result from inadequate packaging at the time of dispatch or from the condition of the product itself. As a logistics company, we are responsible only for transport and delivery and cannot process a refund or reshipment directly.\nWe recommend that you contact the seller or the e-commerce platform directly, explain the damage to the contents, and request a refund, replacement, or claim. If needed, we can provide the delivery records for this shipment.\nWe apologize again for the inconvenience.\nBest regards,\nJason"
    },
    {
      no: 24,
      l1: "服务类",
      l2: "投诉快递员",
      l3: "快递员服务态度差",
      pod: "/",
      sub: "投诉快递员-服务态度",
      plan: "安抚致歉，规范行为",
      sop: "",
      zh: "您好：\n我是 SpeedX 客服部门的 Jason。\n感谢您就快递服务提出的反馈。我们对不满意的配送体验深表歉意。我们理解您的顾虑，并非常重视此事。\n您的反馈已被记录。我们将对涉事快递员采取适当的纠正和纪律措施，包括重新培训，以防止类似情况再次发生。您的反馈也将用于改善我们的服务质量和内部培训。\n出于隐私和安全原因，并根据适用的隐私法律及我们的内部政策，我们无法提供涉事快递员的信息。\n感谢您的理解与耐心。如果您还有任何问题，请回复本邮件。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nThank you for your feedback regarding the courier service. We sincerely apologize for the unsatisfactory delivery experience. We understand your concern and take this matter seriously.\nYour feedback has been recorded. We will take appropriate corrective and disciplinary action with the courier involved, including retraining, to prevent similar situations from happening again. Your feedback will also be used to improve our service quality and internal training.\nFor privacy and security reasons, and in accordance with applicable privacy laws and our internal policies, we are unable to provide information about the courier involved.\nThank you for your understanding and patience. If you have any further questions, please reply to this email.\nBest regards,\nAngelcia"
    },
    {
      no: 25,
      l1: "服务类",
      l2: "投诉快递员",
      l3: "快递员暴力投递",
      pod: "/",
      sub: "投诉快递员-暴力投递（无破损/无证据）",
      plan: "未损坏/证据不足→安抚致歉\n货物损坏→按破损流程处理",
      sop: "",
      zh: "您好，\n我是 SpeedX 客服部门的 Jason。\n感谢您联系我们。对于快递员处理您包裹时给您带来的不愉快体验，我们深表歉意。我们非常重视您的反馈。\n如果您有关于此事件的任何相关证据，请提供给我们，以便我们核实情况。\n我们不会逃避责任。该配送司机也将被追究责任，并将受到纪律处分或罚款。今后，我们将加强对我司司机的培训，以防止类似事件再次发生。\n我们再次诚挚致歉。感谢您的理解与耐心。\n此致，\nJason",
      en: "Dear Customer,\nThis is Jason from SpeedX Customer Service department.\nThank you for contacting us. We sincerely apologize for the unpleasant experience regarding the courier's handling of your package. We take your feedback very seriously.\nIf you have any relevant evidence regarding this incident, please provide it so that we can verify the situation.\nWe will not evade our responsibilities. The delivery driver will also be held accountable and will be subject to disciplinary measures or fines. Moving forward, we will strengthen training for our drivers to prevent similar incidents from recurring.\nWe sincerely apologize again. We appreciate your understanding and patience.\nBest regards,"
    },
    {
      no: 26,
      l1: "服务类",
      l2: "投诉快递员",
      l3: "快递员偷盗",
      pod: "/",
      sub: "投诉快递员-疑似偷窃",
      plan: "安抚 → 核实是否可提供居住相关凭证 / 信息（证明①我司快递员②偷盗行为） → 上报派送服务质量问题件",
      sop: "",
      zh: "您好，\n我是 SpeedX 客服部门的 Jason。\n我们理解您的沮丧，也非常抱歉您的包裹在派送后被盗。我们已阅读您关于快递员可能存在行为的说明，并对标准流程导致这种情况感到遗憾。\n但需要提醒您的是，根据我们的销售条款，对于在派送已通过照片证据确认后发生的被盗，我们无法退款，除非有监控录像能够证明发生了什么。事实上，一旦派送完成，快递员的责任以及我们作为其方的责任也随之终止。\n我们建议您向执法部门报案，报告包裹在派送后被不明人员盗取的情况。希望有关部门能帮助您解决此事。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nWe understand your frustration and are truly sorry about the theft of the package after delivery. We have read your note about the courier’s possible behavior, and we regret that the standard procedure led to this situation.\nHowever, it is important to remember that, as provided in our terms of sale, we cannot issue refunds for thefts that occur after delivery has been confirmed by photographic evidence, unless there are video surveillance recordings proving what happened. Once delivery is completed, in fact, the courier’s liability, and therefore ours as well, ends.\nWe suggest that you file a report with the law enforcement authorities, reporting the theft of the package after delivery by unknown persons. We hope the authorities can help you resolve the situation.\nBest regards,\nJason"
    },
    {
      no: 27,
      l1: "服务类",
      l2: "投诉快递员",
      l3: "派送失败原因与实际不符",
      pod: "/",
      sub: "投诉快递员-派送失败原因与实际不符",
      plan: "用户诉求投诉 → 安抚致歉，规范行为 → 尽快配送",
      sop: "",
      zh: "您好：\n我是 SpeedX 客服部门的 Jason。\n我们诚挚地为预约取件因司机失误而被错过致歉。请确认一个方便的时间，以便我们与运营团队协调，尽快安排再次上门取件。\n对于造成的不便，我们深表歉意，并感谢您的理解。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nWe sincerely apologize that the scheduled pickup was missed due to a driver error. Kindly confirm a convenient time for the pickup so we may coordinate with the operations team to arrange another collection attempt promptly.\nWe apologize for any inconvenience caused and appreciate your understanding.\nBest regards,\nJason"
    },
    {
      no: 28,
      l1: "服务类",
      l2: "投诉快递员",
      l3: "POD图片侵犯隐私",
      pod: "/",
      sub: "POD图片侵犯隐私",
      plan: "安抚致歉 → 数据勘误，删除POD图片",
      sop: "",
      zh: "您好：\n我是 SpeedX 客服部门的 Jason。\n感谢您向我们反映这一情况。对于快递员在拍摄投递照片（POD）时涉及您的个人信息，给您带来困扰，我们深表歉意。\n我们非常重视客户隐私。根据适用的隐私法律法规及我们的内部政策，我们已记录该问题并提交数据勘误处理，相关照片将被删除或进行脱敏处理；同时，我们会对涉事快递员进行提醒与培训，防止类似情况再次发生。\n感谢您的理解与支持。如有任何其他问题，请回复此邮件。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nThank you for bringing this matter to our attention. We sincerely apologize for the concern caused by the courier's proof-of-delivery photo (POD) including your personal information.\nWe take customer privacy very seriously. In accordance with applicable privacy laws and our internal policies, we have recorded this issue and submitted it for data correction; the relevant photo will be deleted or redacted. We will also remind and retrain the courier involved to prevent this from happening again.\nThank you for your understanding and support. If you have any other questions, please reply to this email.\nBest regards,\nJason"
    },
    {
      no: 29,
      l1: "服务类",
      l2: "投诉快递员",
      l3: "未按要求妥投",
      pod: "/",
      sub: "未按要求妥投",
      plan: "安抚致歉 → 上报派送服务质量问题件",
      sop: "",
      zh: "您好：\n我是 SpeedX 客服部门的 Jason。\n感谢您联系我们。对于快递员未按照您在下单或发货时告知的偏好或授权方式投递包裹，给您带来的不便，我们深表歉意。\n我们已记录您反馈的情况，并已将其作为派送服务质量问题上报至相关部门，涉事快递员将接受相应的提醒、培训或纪律处理。同时，我们会加强派送规范的培训，避免类似情况再次发生。\n如您的包裹仍未收到，请告知我们，我们将尽快为您安排重新派送，或协助您进行进一步核查。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nThank you for contacting us. We sincerely apologize that the courier did not deliver your package in accordance with the preferences or authorizations you provided at the time of ordering or shipping.\nWe have recorded your feedback and reported it as a delivery service quality issue to the relevant team. The courier involved will receive appropriate reminders, retraining, or disciplinary action. We will also strengthen training on delivery standards to prevent similar situations from recurring.\nIf you still have not received your package, please let us know and we will arrange a redelivery as soon as possible or assist you with further verification.\nBest regards,\nJason"
    },
    {
      no: 30,
      l1: "服务类",
      l2: "投诉快递员",
      l3: "包裹以外的财物损坏",
      pod: "/",
      sub: "包裹以外的财物损坏",
      plan: "安抚致歉 → 核实是否可提供证据证明我司快递员故意损坏财物的行为 → 上报派送服务质量问题件",
      sop: "",
      zh: "您好：\n我是 SpeedX 客服部门的 Jason。\n感谢您联系我们。对于快递员在派送过程中造成您包裹以外财物损坏的情况，我们深表歉意，也完全理解您的心情。\n我们已记录您的反馈并上报派送服务质量问题。为了进一步核实并明确责任，请您提供相关证据，例如现场照片或视频、监控录像，或其他能够反映损坏发生过程的材料。\n收到材料后，我们将立即展开核查。如核查确认责任在我们，我们将依照相关规定处理，并加强对快递员的培训与管理。\n感谢您的理解与配合。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nThank you for contacting us. We sincerely apologize that the courier caused damage to property other than your package during delivery, and we fully understand how you feel.\nWe have recorded your feedback and reported it as a delivery service quality issue. To verify the matter further and clarify responsibility, please provide relevant evidence, such as on-site photos or videos, CCTV footage, or any other material showing how the damage occurred.\nOnce we receive these materials, we will start the verification immediately. If the damage is confirmed to be our responsibility, we will handle it in accordance with the relevant rules and strengthen the training and management of our couriers.\nThank you for your understanding and cooperation.\nBest regards,\nJason"
    },
    {
      no: 31,
      l1: "服务类",
      l2: "投诉客服",
      l3: "服务态度问题",
      pod: "/",
      sub: "投诉客服-服务态度",
      plan: "投诉客服本人服务态度：态度恶劣、辱骂、抢话、挂机等服务态度类",
      sop: "",
      zh: "您好：\n我是 SpeedX 客服部门的 Jason。\n感谢您向我们反馈本次服务体验。对于我们的客服人员在沟通过程中出现服务态度不当的情况，给您带来不愉快的体验，我们深表歉意。\n我们非常重视您的反馈，已将该情况记录并提交客服管理团队核实。相关客服人员将接受提醒、再培训及相应的内部处理。我们也会加强服务规范与沟通技巧的培训，防止类似情况再次发生。\n再次向您致以歉意，并感谢您的理解与监督。如需进一步说明，请回复此邮件。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nThank you for your feedback regarding this service experience. We sincerely apologize for the unpleasant experience caused by inappropriate service attitude on the part of our customer service agent during the conversation.\nWe take your feedback very seriously and have recorded the matter and referred it to our customer service management team for review. The agent involved will receive reminders, retraining, and appropriate internal handling. We will also strengthen training on service standards and communication skills to prevent this from happening again.\nWe apologize to you once again and thank you for your understanding and supervision. If you need any further clarification, please reply to this email.\nBest regards,\nJason"
    },
    {
      no: 32,
      l1: "服务类",
      l2: "系统问题反馈",
      l3: "系统不满意",
      pod: "/",
      sub: "系统体验反馈",
      plan: "安抚 → 记录问题 → 重视反馈 → 后续优化",
      sop: "",
      zh: "您好：\n我是 SpeedX 客服部门的 Jason。\n感谢您向我们反馈在使用系统过程中遇到的问题。对于由此给您带来的不便，我们深表歉意。\n我们已将您反馈的问题详细记录，并转交至相关团队进行评估与优化。您的建议对我们非常重要，我们会持续改进系统功能，努力为您提供更顺畅的使用体验。\n如问题仍然存在，请提供相关截图或具体操作步骤，以便我们进一步排查。感谢您的理解与支持。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nThank you for sharing the issues you encountered while using our system. We sincerely apologize for the inconvenience caused.\nWe have recorded the details of the problem you reported and forwarded them to the relevant team for evaluation and improvement. Your suggestions are very important to us, and we will continue to improve our system and features to provide you with a smoother experience.\nIf the problem persists, please send us screenshots or the specific steps you took so that we can investigate further. Thank you for your understanding and support.\nBest regards,\nJason"
    },
    {
      no: 33,
      l1: "服务类",
      l2: "正向反馈",
      l3: "表扬客服人员",
      pod: "/",
      sub: "表扬客服人员",
      plan: "表扬客服本人：感谢认可 → 表示开心 → 用心服务\n表扬其他客服：感谢表扬 → 记录转达 → 继续做好服务",
      sop: "",
      zh: "您好：\n我是 SpeedX 客服部门的 Jason。\n非常感谢您对我们客服工作的认可与鼓励，看到您的肯定，我们感到十分开心。\n我们会将您的表扬记录下来，并转达给相关客服人员。您的认可对我们而言是最大的鼓励，我们会继续用心服务每一位客户，不断提升服务质量。\n再次感谢您的支持，祝您生活愉快！\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nThank you very much for your recognition and encouragement of our customer service work. We are delighted to see your positive feedback.\nWe will record your compliment and pass it on to the customer service agent concerned. Your recognition means a great deal to us, and we will continue to serve every customer with dedication and keep improving our service quality.\nThank you again for your support. We wish you all the best.\nBest regards,\nJason"
    },
    {
      no: 34,
      l1: "服务类",
      l2: "正向反馈",
      l3: "表扬快递员",
      pod: "/",
      sub: "表扬快递员",
      plan: "感谢表扬 → 记录转达 → 继续做好服务",
      sop: "",
      zh: "您好：\n我是 SpeedX 客服部门的 Jason。\n非常感谢您对我们快递员服务的肯定与表扬。\n我们已将您的表扬记录下来，并将转达给相关快递员。您的认可对一线同事而言是很大的鼓励。我们会继续努力，为每一位客户提供更好的派送服务。\n再次感谢您的支持，祝您生活愉快！\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nThank you very much for your recognition and praise of our courier's service.\nWe have recorded your compliment and will pass it on to the courier concerned. Your recognition is a great encouragement to our frontline colleagues. We will continue to work hard to provide better delivery service to every customer.\nThank you again for your support. We wish you all the best.\nBest regards,\nJason"
    },
    {
      no: 35,
      l1: "时效类",
      l2: "催派类",
      l3: "时效内催派【外部轨迹断更≤2天】",
      pod: "/",
      sub: "催派-刚到转运中心",
      plan: "告知包裹正常运输中→提醒耐心等待",
      sop: "",
      zh: "您好，\n我是 SpeedX 客服部门的 Jason。\n很抱歉您尚未收到订单。根据我们的系统，您的包裹已抵达我们的仓库。请您耐心等待派送，我们会尽快将包裹分配给快递员。\n如有任何问题，请回复此邮件。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nWe are sorry that you have not yet received your order.According to our system, your package has arrived at our warehouse.Please kindly wait patiently for the delivery, which will be assigned to the courier as soon as possible.\nIf you have any questions, please reply to this email.\nBest regards,\nJason"
    },
    {
      no: 36,
      l1: "时效类",
      l2: "催派类",
      l3: "时效内催派【外部轨迹断更≤2天】",
      pod: "/",
      sub: "催派",
      plan: "告知包裹正常运输中→提醒耐心等待",
      sop: "",
      zh: "您好：\n我是 SpeedX 客服部门的 Jason。\n我们为配送延迟致歉，并真诚地为让您等待感到抱歉。我们将尽快安排配送。请您耐心等待并保持联系。\n如果您有任何问题，请回复本邮件。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nWe apologize for the delivery delay and are sincerely sorry for the wait.We will arrange the delivery as soon as possible. Please be patient and stay in touch.\nIf you have any questions, please reply to this email.\nBest regards,\nJason"
    },
    {
      no: 37,
      l1: "时效类",
      l2: "催派类",
      l3: "时效内催派【外部轨迹断更≤2天】",
      pod: "/",
      sub: "询问具体日期",
      plan: "告知包裹正常运输中→提醒耐心等待",
      sop: "",
      zh: "您好：\n我是 SpeedX 客服部门的 Jason。\n感谢您联系我们。很抱歉，我们无法确认确切的派送日期和星期。我们会尽快安排派送，预计在 1 至 3 天内完成。您可以告知偏好的时间段（例如：上午或下午），我们会尽力将该请求转达给快递员。\n如有任何问题，请回复此邮件。\n此致\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nThank you for contacting us. We are sorry that we cannot confirm the exact delivery date and day. We will arrange the delivery as soon as possible, within 1–3 days.You can indicate a preferred time slot (for example: morning or afternoon), and we will do our best to forward the request to the courier.\nIf you have any questions, please reply to this email.\nBest regards,\nJason"
    },
    {
      no: 38,
      l1: "时效类",
      l2: "催派类",
      l3: "时效内催派【外部轨迹断更≤2天】",
      pod: "/",
      sub: "询问具体时间",
      plan: "告知包裹正常运输中→提醒耐心等待",
      sop: "",
      zh: "您好：\n我是 SpeedX 客服部的 Jason。\n感谢您联系我们。很抱歉，我们无法确认确切的派送日期和具体星期几。我们将尽快安排发货/派送，预计在 1–3 天内完成。\n如果您有任何问题，请回复此邮件。\n此致\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nThank you for contacting us. We are sorry that we are unable to confirm the exact delivery date and day. We will arrange the shipment as soon as possible, within 1–3 days.\nIf you have any questions, please reply to this email.\nBest regards,\nJason"
    },
    {
      no: 39,
      l1: "时效类",
      l2: "催派类",
      l3: "时效内催派【外部轨迹断更≤2天】",
      pod: "/",
      sub: "快递员取件",
      plan: "告知包裹正常运输中→提醒耐心等待",
      sop: "",
      zh: "您好：\n我是 SpeedX 客服部门的 Jason。\n您的包裹已分配给快递员，我们将在 1 至 3 天内为您派送。请耐心等待并保持联系。很抱歉我们无法确认确切的派送日期。\n如有任何问题，请回复此邮件。\n此致\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nYour package has been assigned to a courier, and we will deliver it to you within 1 to 3 days. Please wait patiently and stay in touch. We apologize for not being able to confirm the exact delivery date.\nIf you have any questions, please reply to this email.\nBest regards,\nJason"
    },
    {
      no: 40,
      l1: "时效类",
      l2: "催派类",
      l3: "时效内催派【外部轨迹断更≤2天】",
      pod: "/",
      sub: "重新派送",
      plan: "告知包裹正常运输中→提醒耐心等待",
      sop: "",
      zh: "您好：\n我是 SpeedX 客服部的 Jason。\n感谢您告知我们情况。很抱歉您尚未收到包裹。我们将为您安排重新派送。\n很抱歉我们无法确认确切的派送日期。我们估计您的包裹将在3天内重新派送。\n如有任何问题，请回复此邮件。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nThank you for letting us know the situation. We are sorry that you have not received your parcel yet. We will arrange for a redelivery for you.\nWe apologize for not being able to confirm the exact delivery date. We estimate that your package will be redelivered within 3 days.\nIf you have any questions, please reply to this email.\nBest regards,\nJason"
    },
    {
      no: 41,
      l1: "时效类",
      l2: "催派类",
      l3: "时效内催派【外部轨迹断更≤2天】",
      pod: "/",
      sub: "退回转运中心后重派",
      plan: "告知包裹正常运输中→提醒耐心等待",
      sop: "",
      zh: "您好：\n我是 SpeedX 客服部的 Jason。\n感谢您的来信。对于您尚未收到包裹以及由此给您带来的不便，我们深表歉意。根据系统物流轨迹，您的包裹目前位于仓库。我们预计您的包裹将在 3 天内重新派送。请耐心等待。感谢您的理解。\n如果您有任何问题，请回复此邮件。\n此致\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nThank you for your email. We sincerely apologize that you have not received your package and the inconvenience caused. According to the system tracks, your package is currently in the warehouse. We estimate that your package will be redelivered within 3 days. Please wait patiently. Thank you for your understanding.\nIf you have any questions, please reply to this email.\nBest regards,\nJason"
    },
    {
      no: 42,
      l1: "时效类",
      l2: "催派类",
      l3: "时效内催派【外部轨迹断更≤2天】",
      pod: "/",
      sub: "错分件",
      plan: "告知包裹正常运输中→提醒耐心等待",
      sop: "",
      zh: "您好，\n我是 SpeedX 客服部门的 Jason。\n感谢您联系我们。非常抱歉您尚未收到包裹。由于我们内部的派送安排，派送时间可能会有所延迟。我们目前无法提供确切的派送时间。\n对于造成的不便，我们深表歉意，并感谢您的理解。\n如果您有任何其他问题，请随时联系我们。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nThank you for contacting us. We are very sorry that you have not received your package.Delivery times may be delayed due to our internal delivery arrangements.We are currently unable to provide an exact delivery time.\nWe are very sorry for the inconvenience and thank you for your understanding.\nIf you have any other questions, please do not hesitate to contact us.\nBest regards,\nJason"
    },
    {
      no: 43,
      l1: "时效类",
      l2: "催派类",
      l3: "催派-异常情况",
      pod: "/",
      sub: "催派-不可抗力（车抛锚等意外）",
      plan: "告知不可抗力（车辆故障等）导致延误 → 安抚 → 已安排接驳并尽快派送",
      sop: "催派",
      zh: "您好：\n我是 SpeedX 客服部门的 Jason。\n感谢您的来信。由于承运车辆途中出现故障（不可抗力因素），您的包裹派送出现延迟，给您带来的不便我们深表歉意。\n我们已安排其他车辆接驳，会尽快完成派送。请您耐心等待并保持电话畅通，以便快递员与您联系。\n如有任何问题，请回复此邮件。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nThank you for your message. Due to an unforeseen event (a vehicle breakdown during transport), the delivery of your package has been delayed. We sincerely apologize for the inconvenience caused.\nWe have arranged another vehicle to take over the shipment and will complete the delivery as soon as possible. Please be patient and keep your phone available so that the courier can contact you.\nIf you have any questions, please reply to this email.\nBest regards,\nJason"
    },
    {
      no: 44,
      l1: "时效类",
      l2: "催派类",
      l3: "时效外催派【外部轨迹断更>2天】",
      pod: "/",
      sub: "催派-轨迹断更2-7天",
      plan: "安抚 → 上报催派件，进行调查跟踪",
      sop: "",
      zh: "您好：\n我是 SpeedX 客服部门的 Jason。\n感谢您的来信。对于您的包裹物流信息长时间没有更新、配送出现延迟，给您带来的担心与不便，我们深表歉意。\n根据系统信息，您的包裹目前仍处于正常运输流程中。我们已向承运伙伴提交加急查询，催促其尽快更新物流轨迹并完成派送。\n请您再耐心等待几天，我们会持续跟进。一旦收到最新进展，将第一时间通知您。如有任何问题，请回复此邮件。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nThank you for your message. We sincerely apologize for the concern and inconvenience caused by the lack of tracking updates and the delay in the delivery of your package.\nAccording to our system, your package is still within the normal transport process. We have submitted an expedited inquiry to our carrier partner, urging them to update the tracking information and complete the delivery as soon as possible.\nPlease bear with us for a few more days while we continue to follow up. We will notify you as soon as we receive any updates. If you have any questions, please reply to this email.\nBest regards,\nJason"
    },
    {
      no: 45,
      l1: "时效类",
      l2: "催派类",
      l3: "时效外催派【外部轨迹断更>2天】",
      pod: "/",
      sub: "催派-轨迹断更7-14天",
      plan: "安抚 → 上报催派件，进行调查跟踪",
      sop: "",
      zh: "您好，\n我是 SpeedX 客服部门的 Jason。\n我们真诚地为造成的不便致歉。您的订单配送出现了延迟。我们正在催促快递公司尽快完成派送。\n如有任何问题，请回复此邮件。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nWe sincerely apologize for the inconvenience. The delivery of your order has been delayed. We are urging the courier to complete the delivery as soon as possible.\nIf you have any questions, please reply to this email.\nBest regards,\nJason"
    },
    {
      no: 46,
      l1: "时效类",
      l2: "催派类",
      l3: "时效外催派【外部轨迹断更>2天】",
      pod: "/",
      sub: "催派-轨迹断更>14天",
      plan: "安抚 → 上报催派件，进行调查跟踪",
      sop: "",
      zh: "您好：\n我是 SpeedX 客服部的 Jason。\n您的订单似乎长时间没有更新，可能已经丢失。我们建议您联系卖家申请退款。\n我们将尽一切努力确保此类情况不再发生。感谢您的理解与耐心。\n此致\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nIt appears that your order has not been updated for a long time and may have been lost.We recommend that you contact the seller to request a refund.\nWe will make every effort to ensure that situations like this do not happen again. Thank you for your understanding and patience.\nBest regards,\nJason"
    },
    {
      no: 47,
      l1: "时效类",
      l2: "催派类",
      l3: "时效外催派【外部轨迹断更>2天】",
      pod: "/",
      sub: "催派-有内部轨迹无外部轨迹",
      plan: "安抚 → 上报催派件，进行调查跟踪",
      sop: "",
      zh: "您好：\n我是 SpeedX 客服部门的 Jason。\n感谢您就您的包裹来信。您的包裹目前仍处于正常配送流程中。不过，我们理解长时间没有物流跟踪更新让您感到担忧。\n我们已向配送站点提交了初步加急请求，要求他们优先处理您的包裹，并尽快更新物流跟踪信息。\n感谢您的反馈。对于给您带来的不便，我们深表歉意。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nThank you for your message regarding your package. Your package is currently still in the normal delivery process. However, we understand that the lack of tracking updates for a long time has caused you concern.\nWe have submitted an initial expedite request to the delivery station, asking them to prioritize your package and update the tracking information as soon as possible.\nThank you for your feedback. We sincerely apologize for the inconvenience.\nBest regards,\nJason"
    },
    {
      no: 48,
      l1: "时效类",
      l2: "催派类",
      l3: "催派已签收",
      pod: "/",
      sub: "催派-客服回复邮件时发现包裹已签收",
      plan: "告知包裹已签收",
      sop: "",
      zh: "您好，\n我是 SpeedX 客服部门的 Jason。\n感谢您联系我们。您的包裹已送达。如果您尚未收到，请查看快递员拍摄的 POD作为凭证。\nPOD 1\nPOD 2\nPOD 3\n如果您有任何其他问题，请随时联系我们。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nThank you for contacting us. Your package has been delivered.If you have not received it, please check the POD taken by the courier as proof.\nPOD 1\nPOD 2\nPOD 3\nIf you have any other questions, please do not hesitate to contact us.\nBest regards,\nJason"
    },
    {
      no: 49,
      l1: "需求类",
      l2: "客户查件",
      l3: "签入前查件",
      pod: "/",
      sub: "查件-转运中心签入前",
      plan: "告知物流节点 → 我司暂未收到包裹 → 引导联系上游客户确认",
      sop: "",
      zh: "您好：\n我是 SpeedX 客服部门的Jason。\n感谢您联系我们。我们已正确更新了系统中的收据信息。您的包裹抵达美国仓库后，我们将尽快为您派送。请您在接下来的几天内耐心等待收货。\n如有任何问题，请回复此邮件。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nThank you for contacting us. We have correctly updated the receipt data in our system. We will deliver your package as soon as possible after it arrives in the United States at our warehouse. We kindly ask you to wait for delivery in the coming days.\nIf you have any questions, please reply to this email.\nBest regards,\nJason"
    },
    {
      no: 50,
      l1: "需求类",
      l2: "客户查件",
      l3: "签入前查件",
      pod: "/",
      sub: "查件-完成清关但未到转运中心",
      plan: "告知物流节点 → 我司暂未收到包裹 → 引导联系上游客户确认",
      sop: "",
      zh: "您好：\n我是 SpeedX 客服部门的Jason。\n我们通知您，您的包裹已完成清关，但尚未到达我们的仓库。一旦我们收到指令，包裹将随即被分配给快递员。请您耐心等待。供您参考，您也可以在我们的网站 https://speedx.io/ 上跟踪物流信息。\n如有任何问题，请回复此邮件。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nWe inform you that your parcel has cleared customs, but it is not yet in our warehouse.As soon as we receive the order, it will subsequently be assigned to the courier. Please be patient.For your information, you can also track it on our website:https://speedx.io/\nIf you have any questions, please reply to this email.\nBest regards,\nJason"
    },
    {
      no: 51,
      l1: "需求类",
      l2: "客户查件",
      l3: "签入前查件",
      pod: "/",
      sub: "查件-包裹未到SPX仓库",
      plan: "告知物流节点 → 我司暂未收到包裹 → 引导联系上游客户确认",
      sop: "",
      zh: "您好，\n我是 SpeedX 客服部门的 Jason。\n我们目前尚未从卖家处收到您的包裹入库。我们建议您联系原始发件人或电商平台客服，以获取进一步信息。您可以访问 https://speedx.io/ 跟踪物流状态。\n您会看到“SpeedX 已收到订单信息”这一提示，这表示我们仅收到了发货数据并生成了追踪号，但包裹尚未交付并由 SpeedX 接收。\n如果您有关于该运单的进一步证据，请发送给我们：我们将调查配送状态。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nWe have not yet received your parcel from the seller at our warehouse.We invite you to contact the original sender or the customer service of the e-commerce platform for further information.You can track the shipment status at https://speedx.io/.\nThe wording you will find, “SpeedX has received order information,” indicates that we have only received the shipment data and generated a tracking number, but the parcel has not yet been delivered to and received by SpeedX.\nIf you have further evidence regarding the shipment, please send it to us: we will investigate the delivery status.\nBest regards,\nJason"
    },
    {
      no: 52,
      l1: "需求类",
      l2: "客户查件",
      l3: "退件后查件",
      pod: "/",
      sub: "查件-已退回商家",
      plan: "告知物流节点 → 退回状态无法操作 → 引导联系上游客户确认",
      sop: "",
      zh: "您好：\n我是 SpeedX 客服部门的Jason。\n很抱歉通知您，由于长时间未收到发货指示，您的包裹已被退回给卖家或电商平台。\n如需重新派送，请您直接联系您的卖家。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nWe regret to inform you that, as we have not received shipping instructions for a long period, your parcel has been returned to the seller or e-commerce platform.\nFor redelivery, we kindly invite you to contact your seller directly.\nBest regards,\nJason"
    },
    {
      no: 53,
      l1: "需求类",
      l2: "需求变更",
      l3: "信息修改",
      pod: "/",
      sub: "修改地址-核实地址",
      plan: "若需核实先核实信息→ 修改信息→ 告知已协助修改下单信息",
      sop: "",
      zh: "您好，\n我是 SpeedX 客服部门的 Jason。\n感谢您的耐心等待。为避免就确切的派送位置产生任何潜在误解，能否请您确认一下该位置，以确保其准确无误？\n谷歌截图\n谷歌链接\n谷歌经纬度\n如果确认无误，我们将为您更新地址。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nThank you for your patience. To avoid any potential misunderstanding regarding the exact delivery location, could you kindly confirm it to ensure that it is correct?\nGoogle Maps screenshot\nGoogle Maps link\nGoogle Maps latitude and longitude\nIf so, we will update the address for you.\nBest regards,\nJason"
    },
    {
      no: 54,
      l1: "需求类",
      l2: "需求变更",
      l3: "信息修改",
      pod: "/",
      sub: "修改地址-要谷歌地图可查地址",
      plan: "若需核实先核实信息→ 修改信息→ 告知已协助修改下单信息",
      sop: "",
      zh: "您好，\n我是 SpeedX 客服部门的 Jason。\n我们无法在谷歌地图上定位到您指定的地址。为确保货物正确派送，请您提供更详细的信息。能否请您向我们提供派送地点在谷歌地图上的截图、经纬度以及位置共享链接？\n如果您有任何其他问题，请随时联系我们。感谢您的理解。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nWe are unable to locate the address specified on Google Maps.To ensure the correct delivery of the goods, please provide further details.Could you kindly provide us with a screenshot of the delivery location on Google Maps, the latitude and longitude, and a location sharing link?\nIf you have any further questions, please do not hesitate to contact us. Thank you for your understanding.\nBest regards,\nJason"
    },
    {
      no: 55,
      l1: "需求类",
      l2: "需求变更",
      l3: "信息修改",
      pod: "/",
      sub: "修改信息-下单信息不完整",
      plan: "若需核实先核实信息→ 修改信息→ 告知已协助修改下单信息",
      sop: "",
      zh: "您好，\n我是 SpeedX 客服部门的 Jason。\n您提供的下单信息不完整。请填写以下所需信息。\n请注意，我们不与自提点、烟草店、快递柜或邮局合作，也不向其派送。\n收件人全名：\n电话号码：\n完整地址：\n邮政编码和城市：\n门牌号：\n任何门禁密码（例如：楼栋入口门）：\n对讲机/门禁对讲上的姓名：\n感谢您的及时协助。这将有助于我们尽可能顺利地完成您的派送。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nThe information you provided regarding your order is incomplete. Please fill in the required details below.\nPlease note that we do not partner with and do not deliver to pickup points, tobacco shops, lockers, or post offices.\nRecipient’s full name:\nPhone number:\nFull address:\nPostal code and city:\nStreet number:\nAny access code (e.g., building entrance door):\nName on the intercom:\nThank you for your prompt help. This will help us complete your delivery as smoothly as possible.\nBest regards,\nJason"
    },
    {
      no: 56,
      l1: "需求类",
      l2: "需求变更",
      l3: "信息修改",
      pod: "/",
      sub: "投递失败：大楼关闭/周末/节假日",
      plan: "若需核实先核实信息→ 修改信息→ 告知已协助修改下单信息",
      sop: "",
      zh: "您好：\n我是 SpeedX 客服部门的 Jason。\n根据我们的记录，您的订单尚未送达，原因是“投递失败：大楼关闭/周末/节假日”。\n请问您能否告知您偏好的配送时间段（例如上午/下午）？我们将尽快安排派送。\n请注意，我们不与自提点、烟草店、快递柜或邮局合作，也不提供派送至这些地点的服务。\n此致\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nAccording to our records, your order has not been delivered; the reason is “Attempted Delivery: Building Closed/Weekend/Holiday.”\nCould you please let us know your preferred delivery time window (e.g., morning/afternoon)? We will arrange the delivery as soon as possible.\nPlease note that we do not partner with and do not deliver to pickup points, tobacco shops, lockers, or post offices.\nBest regards,\nJason"
    },
    {
      no: 57,
      l1: "需求类",
      l2: "需求变更",
      l3: "信息修改",
      pod: "/",
      sub: "投递失败：无法进入/无法投递",
      plan: "若需核实先核实信息→ 修改信息→ 告知已协助修改下单信息",
      sop: "",
      zh: "您好：\n我是 SpeedX 客服部门的 Jason。\n根据我们的记录，您的订单尚未送达，原因是“无法进入/无法投递”。\n请问您能否告知您偏好的配送时间段（例如上午/下午），以及任何进入指引（例如门禁码、门铃、楼门入口）？我们将尽快安排派送。\n请注意，我们不与自提点、烟草店、快递柜或邮局合作，也不提供派送至这些地点的服务。\n此致\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nAccording to our records, your order has not been delivered; the reason is “No Access / Undeliverable.”\nCould you please let us know your preferred delivery time window (e.g., morning/afternoon) and any access instructions (e.g., gate code, buzzer, building entrance)? We will arrange the delivery as soon as possible.\nPlease note that we do not partner with and do not deliver to pickup points, tobacco shops, lockers, or post offices.\nBest regards,\nJason"
    },
    {
      no: 58,
      l1: "需求类",
      l2: "需求变更",
      l3: "信息修改",
      pod: "/",
      sub: "投递失败（收件人不在家）",
      plan: "说明投递时收件人不在家 → 询问偏好时间段或放置授权 → 尽快安排再次派送",
      sop: "催派",
      zh: "您好：\n我是 SpeedX 客服部门的 Jason。\n感谢您联系我们。根据我们的记录，您的订单本次未能送达，原因是投递时收件人不在家。对于由此给您带来的不便，我们深表歉意。\n我们将尽快为您安排再次派送。烦请告知您偏好的派送时间段（例如上午或下午），以及是否可以授权将包裹放置在指定位置。请注意，我们不与自提点、烟草店、快递柜或邮局合作，也不提供派送至这些地点的服务。\n如有任何问题，请回复此邮件。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nThank you for contacting us. According to our records, your order could not be delivered because no one was available at the address at the time of the delivery attempt. We sincerely apologize for the inconvenience.\nWe will arrange another delivery attempt as soon as possible. Kindly let us know your preferred delivery time window (for example, morning or afternoon) and whether you authorize us to leave the parcel at a designated place. Please note that we do not partner with and do not deliver to pickup points, tobacco shops, lockers, or post offices.\nIf you have any questions, please reply to this email.\nBest regards,\nJason"
    },
    {
      no: 59,
      l1: "需求类",
      l2: "需求变更",
      l3: "信息修改",
      pod: "/",
      sub: "告知已修改信息（转运中心签入前）",
      plan: "若需核实先核实信息→ 修改信息→ 告知已协助修改下单信息",
      sop: "",
      zh: "您好，\n我是 SpeedX 客服部门的 Jason。\n感谢您联系我们。我们已正确更新了系统中的收货数据。您的包裹抵达美国我们的仓库后，我们将尽快为您派送。请您在接下来的几天内耐心等待派送。\n如有任何问题，请回复此邮件。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nThank you for contacting us. We have correctly updated the receipt data in our system. We will deliver your package as soon as possible after it arrives in the United States at our warehouse. We kindly ask you to wait for delivery in the coming days.\nIf you have any questions, please reply to this email.\nBest regards,\nJason"
    },
    {
      no: 60,
      l1: "需求类",
      l2: "需求变更",
      l3: "信息修改",
      pod: "/",
      sub: "告知已修改信息（转运中心签入后）",
      plan: "若需核实先核实信息→ 修改信息→ 告知已协助修改下单信息",
      sop: "",
      zh: "您好，\n我是 SpeedX 客服部门的 Jason。\n感谢您的耐心等待。我已审核您提供的信息，并已将更新发送给我们的配送团队，以便尽快再次尝试派送。\n如有任何问题，请回复此邮件。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nThank you for your patience. I've reviewed the information you provided, and I sent the update to our delivery team for a reattempt as soon as possible.\nIf you have any questions, please reply to this email.\nBest regards,\nJason"
    },
    {
      no: 61,
      l1: "需求类",
      l2: "需求变更",
      l3: "信息修改",
      pod: "/",
      sub: "告知收到偏好时间段",
      plan: "若需核实先核实信息→ 修改信息→ 告知已协助修改下单信息",
      sop: "",
      zh: "您好，\n我是 SpeedX 客服部门的 Jason。\n感谢您的邮件。我们已收到您提供的信息。我们会通知快递员，如有可能，在您偏好的时间进行派送。\n如有任何问题，请回复此邮件。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nThank you for your email. We have received the information you provided.We will inform the courier to make the delivery, if possible, at your preferred time.\nIf you have any questions, please reply to this email.\nBest regards,\nJason"
    },
    {
      no: 62,
      l1: "需求类",
      l2: "理赔",
      l3: "签收前要求不派送",
      pod: "/",
      sub: "不要包裹且可退给商家（包裹未签收）",
      plan: "",
      sop: "",
      zh: "您好，\n我是 SpeedX 客服部门的 Jason。\n对造成的不便，我们深表歉意。根据您的要求，包裹已退回给卖家。您可以向卖家申请退款，卖家在收到退回的商品后将为您处理退款。\n如有任何问题，请回复此邮件。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nWe apologize for the inconvenience. As per your request, the package has been returned to the seller. You can request a refund from the seller, who will process the refund once the returned item is received.\nIf you have any questions, please reply to this email.\nBest regards,\nJason"
    },
    {
      no: 63,
      l1: "需求类",
      l2: "理赔",
      l3: "用户要求理赔",
      pod: "/",
      sub: "用户要求理赔",
      plan: "安抚情绪→联系上游协商",
      sop: "",
      zh: "您好：\n我是 SpeedX 客服部门的 Jason。\n感谢您联系我们。对于您的包裹出现的问题以及由此给您带来的不便，我们深表歉意，也完全理解您的心情。\n作为物流服务商，SPX 负责包裹的运输与派送，无法直接为您办理退款或赔付。我们已就您反馈的情况联系上游发件方/卖家进行协商，并会在收到回复后第一时间告知您处理结果。\n为便于我们推进处理，请您提供相关凭证，例如包裹及内件照片、投递照片（POD）或运单信息。感谢您的理解与配合。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nThank you for contacting us. We sincerely apologize for the problems with your package and the inconvenience caused, and we fully understand how you feel.\nAs a logistics service provider, SPX is responsible for the transport and delivery of packages and cannot process refunds or compensation directly. We have contacted the original sender/seller regarding the situation you reported and will inform you of the outcome as soon as we receive their reply.\nTo help us move this forward, please provide the relevant evidence, such as photos of the package and its contents, proof-of-delivery photos (POD), or the tracking information. Thank you for your understanding and cooperation.\nBest regards,\nJason"
    },
    {
      no: 64,
      l1: "需求类",
      l2: "要求退件",
      l3: "签收后要求退件",
      pod: "/",
      sub: "签收后要求退件",
      plan: "安抚情绪 → 说明签收后无法退件 → 引导联系上游客户处理",
      sop: "",
      zh: "您好：\n我是 SpeedX 客服部门的 Jason。\n感谢您联系我们。我们理解您希望退回包裹，并对由此给您带来的不便深表歉意。\n由于您的包裹已显示签收，作为物流公司，我们无法直接为您办理退件，也无法收回已完成派送的包裹。关于退货、退款或换货，建议您直接联系卖家或您购买商品的电商平台，由他们为您安排后续流程。\n如有需要，我们可以为您提供本次派送的签收凭证（POD），以便您与卖家沟通。感谢您的理解与配合。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nThank you for contacting us. We understand that you would like to return the package, and we sincerely apologize for the inconvenience caused.\nAs your package has already been shown as delivered, we as a logistics company cannot process a return directly or collect a package that has already been delivered. For a return, refund, or exchange, we recommend that you contact the seller or the e-commerce platform where you made your purchase directly, so that they can arrange the follow-up procedure for you.\nIf needed, we can provide the proof of delivery (POD) for this shipment so that you can communicate with the seller. Thank you for your understanding and cooperation.\nBest regards,\nJason"
    },
    {
      no: 65,
      l1: "其他类",
      l2: "无单号/单号错误",
      l3: "/",
      pod: "/",
      sub: "无运单号",
      plan: "",
      sop: "",
      zh: "您好：\n我是 SpeedX 客服部的 Jason。\n感谢您的耐心等待。为了协助您处理咨询，我们需要您的 SpeedX 追踪单号。如果您没有该单号，请联系您的销售点获取追踪单号。\n如有任何问题，请回复此邮件。\n此致\n敬礼，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nThank you for your patience.We require your SpeedX tracking number to assist with your inquiry.If you don't have that available, please contact your point of sale to obtain the tracking number.\nIf you have any questions, please reply to this email.\nBest regards,\nJason"
    },
    {
      no: 66,
      l1: "其他类",
      l2: "无单号/单号错误",
      l3: "/",
      pod: "/",
      sub: "运单号错误",
      plan: "",
      sop: "",
      zh: "您好，\n我是 SpeedX 客服部门的 Jason。\n感谢您的耐心等待。您提供的追踪号似乎有问题，因为我们的系统无法识别该单号。为了继续为您提供帮助，我们需要一个以 SPX 开头的有效追踪号。如果这是您从购买处收到的追踪号，请联系他们并告知该单号无效。\n如有任何问题，请回复此邮件。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nThank you for your patience.It seems there’s an issue with the tracking number, as it is not recognized in our system. To proceed with assisting you, we’ll need a valid tracking number that begins with SPX. If this is the tracking number you received from your point of sale, please reach out to them to inform them that it is invalid.\nIf you have any questions, please reply to this email.\nBest regards,\nJason"
    },
    {
      no: 67,
      l1: "其他类",
      l2: "无单号/单号错误",
      l3: "/",
      pod: "/",
      sub: "运单号不完整",
      plan: "",
      sop: "",
      zh: "您好，\n我是 SpeedX 客服部门的Jason。\n我们诚挚地为给您造成的困惑致歉。请提供您的完整追踪号，该号码由字母和数字组成。如果号码不完整，我们将无法为您提供支持。\n期待您的回复。\n此致，\nJason",
      en: "Dear,\nThis is Kevin from SpeedX Customer Service department.\nWe sincerely apologize for the Confusion that caused you.Kindly provide your full tracking number, which consists of letters and numbers. Without the complete tracking number, We cannot offer support if the number is incomplete.\nI am looking forward to your reply.\nBest regards，\nKevin Wong"
    },
    {
      no: 68,
      l1: "其他类",
      l2: "单纯进线信息告知（邮件）",
      l3: "/",
      pod: "/",
      sub: "感谢(包裹未签收)",
      plan: "",
      sop: "",
      zh: "您好，\n我是 SpeedX 客服部门的 Jason。\n我们衷心感谢您的理解以及您所展现出的耐心——这些品质我们深表赞赏。\n我们将确保新的派送完全满足您的需求。如果您有任何进一步的要求或需要澄清的事项，请随时与我们联系。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nWe sincerely thank you for your understanding and for the patience you have shown—qualities we deeply appreciate.\nWe will ensure that the new delivery fully meets your needs. Should you have any further requirements or requests for clarification, please do not hesitate to contact us.\nBest regards,\nJason"
    },
    {
      no: 69,
      l1: "其他类",
      l2: "单纯进线信息告知（邮件）",
      l3: "/",
      pod: "/",
      sub: "真诚道歉（包裹未签收）",
      plan: "未签收且需致歉 → 真诚致歉安抚 → 记录问题并尽快跟进",
      sop: "单纯进线信息告知（邮件）",
      zh: "您好：\n我是 SpeedX 客服部门的 Jason。\n非常抱歉给您带来了不愉快的体验。对于您的包裹在派送过程中出现的问题，我们深表歉意。\n我们已记录您反馈的情况，并将尽快跟进处理，同时改进相关流程，避免类似情况再次发生。对于由此给您造成的不便，我们再次表示歉意。\n如有任何问题或需要进一步协助，请回复此邮件。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nWe are very sorry for the unpleasant experience. We sincerely apologize for the problems that occurred during the delivery of your package.\nWe have recorded the situation you reported and will follow up as soon as possible, and we will improve the relevant procedures to prevent this from happening again. We apologize once again for the inconvenience caused to you.\nIf you have any questions or need further assistance, please reply to this email.\nBest regards,\nJason"
    },
    {
      no: 70,
      l1: "其他类",
      l2: "单纯进线信息告知（邮件）",
      l3: "/",
      pod: "/",
      sub: "感谢（包裹已签收）",
      plan: "",
      sop: "",
      zh: "您好，\n我是 SpeedX 客服部门的 Jason。\n很高兴您已收到包裹。我们将继续努力，为客户提供越来越好的服务。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nWe are pleased that you have received your parcel.We will continue to strive to offer our customers an ever-better service.\nBest regards,\nJason"
    },
    {
      no: 71,
      l1: "其他类",
      l2: "单纯进线信息告知（邮件）",
      l3: "/",
      pod: "/",
      sub: "感谢+道歉（包裹已签收）",
      plan: "",
      sop: "",
      zh: "您好：\n我是 SpeedX 客户服务部的 Jason。\n很抱歉给您带来不便，也感谢您的理解。\n我们将努力改进，以提供优质的服务；同时，很高兴您已收到包裹。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nWe are sorry for the inconvenience and thank you for your understanding.\nWe will endeavor to improve in order to provide a quality service, and we are pleased that you have received your parcel.\nBest regards,\nJason"
    },
    {
      no: 72,
      l1: "其他类",
      l2: "合作咨询/服务咨询",
      l3: "/",
      pod: "/",
      sub: "投简历面试",
      plan: "礼貌接待 → 记录需求 → 反馈合作邮箱",
      sop: "",
      zh: "您好，\n为确保选拔流程规范、公平，并遵守现行个人数据处理相关规定，我们不通过客服渠道接收简历或进行面试。请通过我们的官方招聘邮箱联系我们：Jason。届时，您的简历将通过适当渠道转交至我们的人力资源部门。\n感谢您的关注，祝您求职顺利！\n此致，\nJason",
      en: "Dear,\nTo ensure a standardized and fair selection process and to comply with current regulations on personal data processing, we do not accept CVs or conduct interviews through our customer support channels.Please contact us at our official email address for recruitment:Jason. Your CV will then be forwarded to our Human Resources office through the appropriate channels.\nThank you for your interest, and we wish you success in your job search!\nBest regards,\nJason"
    },
    {
      no: 73,
      l1: "其他类",
      l2: "其他类",
      l3: "/",
      pod: "/",
      sub: "商品质量问题",
      plan: "",
      sop: "",
      zh: "您好：\n我是 SpeedX 客服部的 Jason。\n我们理解您的情况。我们需要说明的是，SPX 仅负责包裹派送。以下相关问题：\n1. 制造缺陷；\n2. 与描述不符；\n3. 产品故障或不适用；\n4. 已存在的损坏；\n均属于卖家或购买该产品的电商平台的责任。\n如需快速解决（换货或退款），我们建议您直接联系卖家或电商平台的客服。\n很抱歉我们无法直接为您提供帮助，但希望这些说明能帮助您解决问题。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nWe understand the situation. We would like to clarify that SPX is exclusively responsible for parcel delivery. Any issues related to:\n1.Manufacturing defects；\n2.Differences from the description；\n3.Malfunctions or unsuitability of the product；\n4.Existing damages；\nare the responsibility of the seller or the e-commerce platform from which the product was purchased.\nFor a quick solution (replacement or refund), we recommend that you contact the seller’s or e-commerce platform’s customer service directly.\nWe apologize for not being able to assist you directly, but we hope these instructions will help you resolve the issue.\nBest regards,\nJason"
    },
    {
      no: 74,
      l1: "其他类",
      l2: "其他类",
      l3: "/",
      pod: "/",
      sub: "包裹异味",
      plan: "",
      sop: "",
      zh: "您好：\n感谢您的来信。对于强烈异味给您带来的不愉快体验，我们很抱歉。我已记录您的反馈并升级至相关部门。\n请注意，SpeedX 仅提供派送服务，不对包裹内物品负责。如需退款或补发，请直接联系卖家或电商平台。\n此致\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nThank you for your message. We are sorry for the unpleasant experience with the strong odor. I have recorded your feedback and escalated it to our relevant team.\nPlease note that SpeedX only provides delivery service and is not responsible for the package contents. For a refund or replacement, please contact the seller or the e-commerce platform directly.\nBest regards,\nJason"
    },
    {
      no: 75,
      l1: "其他类",
      l2: "其他类",
      l3: "/",
      pod: "/",
      sub: "想要自提",
      plan: "",
      sop: "",
      zh: "您好，\n我是 SpeedX 客服部门的Jason。\n感谢您联系我们。我们理解您希望亲自领取包裹。但很遗憾地通知您，根据仓库政策，我们不提供自提服务。\n您的包裹将通过我们的标准派送流程寄送到您的地址。请等待快递员完成派送。\n感谢您的理解。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nThank you for contacting us.We understand that you would like to pick up your package in person. However, we regret to inform you that, in accordance with warehouse policy, we do not offer a self-pickup service.\nYour parcel will be shipped to your address via our standard delivery process.Kindly wait for the courier to complete delivery.\nThank you for your understanding.\nBest regards，\nJason"
    },
    {
      no: 76,
      l1: "其他类",
      l2: "其他类",
      l3: "/",
      pod: "/",
      sub: "询问商家",
      plan: "",
      sop: "",
      zh: "您好，\n我是 SpeedX 客服部门的 Jason。\n为保护我们商业合作伙伴的安全与机密，我们无权向第三方提供有关卖家的信息。如需办理退货、退款或换货，请您直接联系卖家或您购买商品的电商平台。SPX 无权代表第三方处理包裹：任何换货、退货或退款流程只能通过原始发件人/卖家发起。\n感谢您的理解。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nTo protect the security and confidentiality of our business partners, we are not authorized to provide information about sellers to third parties.For any return, refund, or replacement requests, we invite you to contact directly the seller or the e-commerce platform where you made your purchase.SPX is not authorized to handle parcels on behalf of third parties: any exchange, return, or refund procedures can be initiated exclusively through the original sender/seller.\nWe thank you for your understanding.\nBest regards,\nJason"
    },
    {
      no: 77,
      l1: "其他类",
      l2: "其他类",
      l3: "/",
      pod: "/",
      sub: "询问发件人",
      plan: "",
      sop: "",
      zh: "您好，\n我是 SpeedX 客服部门的 Jason。\n感谢您联系我们。我们想告知您，SPX 仅负责运输服务，并非您订单的原始发件人。如果您是在网上购买的，您可以直接在您下单的网站上找到卖家的信息。\n感谢您的理解。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nThank you for contacting us. We would like to inform you that SPX is responsible exclusively for the shipping service and is not the original sender of your order. If you made your purchase online, you can find the seller's information directly on the website from which you ordered.\nWe thank you for your understanding.\nBest regards,\nJason"
    },
    {
      no: 78,
      l1: "其他类",
      l2: "其他类",
      l3: "/",
      pod: "/",
      sub: "询问快递员",
      plan: "",
      sop: "",
      zh: "您好：\n我是 SpeedX 客服部门的 Jason。\n为遵守适用的美国数据保护与隐私法律，并保护我们团队成员的隐私，我们无法披露任何关于我们员工的个人身份信息。感谢您的理解。\n如果您需要查询包裹状态，请在我们的网站 https://speedx.io/ 上使用 SPX 跟踪号。\n感谢您的理解。\n此致\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nTo comply with applicable U.S. data protection and privacy laws and protect the privacy of our team members, we cannot disclose any personally identifiable information about our employees. We thank you for your understanding.\nIf you need to check the status of your package, please use the SPX tracking number on our website https://speedx.io/.\nWe thank you for your understanding.\nBest regards,\nJason"
    },
    {
      no: 79,
      l1: "其他类",
      l2: "其他类",
      l3: "/",
      pod: "/",
      sub: "错误投递包裹待取件",
      plan: "",
      sop: "",
      zh: "您好：\n我是 SpeedX 客服部门的 Jason。\n感谢您的耐心，也感谢您将此事告知我们。对于此次错误投递，我们深表歉意。\n我们已记录该跟踪号。由于该包裹并非寄给您，请您不要打开包裹，并将其妥善保管在安全的地方。我们的 SPX 快递员预计将在未来 1–2 天内上门取件。我们会尽快安排取件。\n如您有任何疑问，或需要确认方便的取件时间，请随时与我们联系。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nThank you for your patience and for bringing this matter to our attention. We sincerely apologize for the incorrect delivery.\nWe have noted this tracking number. Since the package was not addressed to you, please keep the package unopened and in a safe place. Our SPX courier will come to pick it up within the next 1–2 days. We will arrange the pickup as soon as possible.\nIf you have any questions or need to confirm a convenient pickup time, please do not hesitate to contact us.\nBest regards,\nJason"
    },
    {
      no: 80,
      l1: "其他类",
      l2: "其他类",
      l3: "/",
      pod: "/",
      sub: "POD和签收类型的解释",
      plan: "",
      sop: "",
      zh: "您好：\n我是 SpeedX 客服部门的 Jason。\n“POD”（“Proof of Delivery”，即“交付证明”）是包裹已交付给收件人的确认。在美国，最常见的方法包括：\n1、照片验证：一张包裹及运单标签的照片。\n2、照片验证：一张包裹在订单指定门牌号处的照片。\n3、客户通过短信或电子邮件授权将包裹留置在特定地点。\n出于美国隐私法规（如 CCPA/CPRA）的原因，我们不能要求或提供包含收件人个人生物识别数据的交付证明。\n我们公司 SpeedX 主要使用照片验证。如果客户/收件人要求查看某次交付的 POD，我们的客服可以随时提供交付的照片证明。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nThe \"\"POD\"\" (\"\"Proof of Delivery\"\") represents confirmation that the parcel has been delivered to the recipient. In the United States, the most common methods include:\nPhoto verification: a photo of the parcel and the shipping label.\nPhoto verification: a photo of the parcel at the street number designated at the time of order.\nAuthorization by the customer to leave the parcel in a specific place via SMS or email.\nFor reasons related to applicable U.S. privacy laws (e.g., CCPA/CPRA), we cannot request or provide proof of delivery containing the recipient's personal biometric data.\nOur company, SpeedX, uses photo verification as its main method. If the customer/recipient requests to view the POD of a delivery, our customer service is available to provide photographic proof of the delivery.\nBest regards,\nJason"
    },
    {
      no: 81,
      l1: "其他类",
      l2: "其他类",
      l3: "/",
      pod: "/",
      sub: "包裹被打开",
      plan: "",
      sop: "",
      zh: "您好，\n我是 SpeedX 客服部门的 Jason。\n对于您收到被打开包裹的不愉快经历，我们深表歉意，并完全理解您的情况。\n美国海关当局可能会对抵达美国的国际包裹进行随机检查。被检查的包裹通常会用特殊胶带重新封好，通常为红色，标有“Customs Inspection（海关检查）”或主管机构的标志。\n我们建议您：\n1. 检查包裹上是否有海关胶带；\n2. 检查内件是否有物品缺失。\n如果您没有找到海关胶带，请回复此邮件并附上包装和内件的照片。我们将立即联系快递公司进行必要的核查。\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nWe apologize for the unpleasant experience of receiving an opened package and fully understand your situation.\nU.S. customs authorities may conduct random inspections on international packages arriving in the United States.Inspected packages are usually resealed with special tape, typically red, marked with “Customs Inspection” or the logo of the competent agency.\nWe recommend that you:\n1.Check for the presence of customs tape on the package;\n2.Check the contents for any missing items.\nIf you do not find the customs tape, please reply to this email attaching photos of the packaging and contents. We will immediately contact the courier to carry out the necessary verifications.\nBest regards,\nJason"
    },
    {
      no: 82,
      l1: "其他类",
      l2: "其他类",
      l3: "/",
      pod: "/",
      sub: "前一封邮件回复错误",
      plan: "",
      sop: "",
      zh: "您好，\n我是 SpeedX 客服部门的 Jason。\n请忽略上一封邮件的内容，并以本邮件为准。\nxxxxxx\n此致，\nJason",
      en: "Dear,\nThis is Jason from SpeedX Customer Service department.\nPlease disregard the content of the previous email and refer to this message.\nxxxxxx\nBest regards,\nJason"
    }
  ]
};
